a = print(input("Digite o 1º Numero: "))
b = print(input("Digite o 2º Numero: "))

print("Soma: "+(a + b))
print("Subtração: "+ (a - b))
print("Multiplicação: "+ (a * b))
print("Divisão: " (a / b))
print("Divisão Inteira: "+(a // b)) 
print("Resto da Divisão: "+(a % b)) 
print("Pontenciação"+(a ** b))